# 本地用(windows)
version: '3.8'
networks:
  pulsar_network:
    external: true
    name: pulsar_network

services:
  prometheus:
    image: prom/prometheus:v2.45.2
    container_name: prometheus
    user: 'root'
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - ./data/prometheus:/prometheus
    restart: unless-stopped
    networks:
      - pulsar_network
    privileged: true
    mem_limit: 500m
  
  # grafana:
  #   image: grafana/grafana-oss:latest
  #   container_name: grafana
  #   user: 'root'
  #   ports:
  #     - '3333:3000'
  #   volumes:
  #     - ./data/grafana:/var/lib/grafana
  #     - ./grafana/provisioning/:/etc/grafana/provisioning/
  #   restart: unless-stopped
  #   networks:
  #     - pulsar_network
  #   privileged: true
  
  # 用來監控 cpu, memory...等資源使用情況
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.5.0
    container_name: node_exporter
    command: '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    user: 'root'
    volumes:
      - ./:/host:ro,rslave
    networks:
      - pulsar_network
    mem_limit: 500m
  
  # 用來監控 docker container 資源使用情況
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    user: 'root'
    command:
      - '-port=8098'
    volumes:
      - ./:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    restart: unless-stopped
    networks:
      - pulsar_network
    mem_limit: 500m